### ISSUE TITLE
How to get socket file descriptor

### ISSUE THREAD

**Issue by aelmahmoudy** [xmpppy/xmpppy#72]
Hello, I am try to update jabber weechat script to the python3 & Updated xmpppy:
https://github.com/aelmahmoudy/weechat-scripts/blob/jabber-py3/python/jabber.py
Yet it still doesn't work. I realized that the value of socket file descriptor after authentication is -1, which I doubt is wrong ! it grts set in line 518 as follows:
`
self.sock = self.client.Connection._sock.fileno()
`
is this method still correct for new xmpppy API ?

**Comment by gdt** [comment]
Class members with _ are not part of the API, I'd say, so no, it wasn't correct before and it still isn't.  But the API should allow this so you can hook into select.

I suggest that you read and understand transport.py.   In particular you didn't say how you were connecting; there is a wrapper for tls.  Probably you should add a sock() method and implement it consistently.

(I'm not part of upstream, and it seems this package is no longer maintained; a fix for TLS in modern python is in a PR open since 2023-11.)

**Comment by amotl** [comment]
Hi. [xmpppy 0.7.2](https://github.com/xmpppy/xmpppy/releases/tag/0.7.2) has been released, including @juanvalino's improvement. Thank you very much.

**Comment by amotl** [comment]
@gdt said:

> In particular you didn't say how you were connecting [...]

Well, @aelmahmoudy referred to [weechat-scripts/jabber.py](https://github.com/aelmahmoudy/weechat-scripts/blob/jabber-py3/python/jabber.py), but yes, it would be so sweet if you could isolate the problem for us by providing a small reproducer we could work on together. Thanks!

**Comment by aelmahmoudy** [comment]
The change in 0.7.2 didn't fix the issue.

@amotl said:

> Well, @aelmahmoudy referred to [weechat-scripts/jabber.py](https://github.com/aelmahmoudy/weechat-scripts/blob/jabber-py3/python/jabber.py), but yes, it would be so sweet if you could isolate the problem for us by providing a small reproducer we could work on together. Thanks!

I will repeat my email to @amotl here:

I have been trying to port weechat's jabber script to python3. This is 
a script using xmpppy to enable weechat users to connect to Jabber. It 
used to work with xmpppy 0.4.1 and python2, but when attempting to 
port it to python3 (& xmpppy 0.7.1), it doesn't work.

My work can be found at:
https://github.com/aelmahmoudy/weechat-scripts/blob/jabber-py3/python/jabber.py

When attempting to debug, I found that it does indeed connect, yet the 
self.sock doesn't seem to get set properly, it gets set at line 518:

self.sock = self.client.Connection._sock.fileno() 

So I added a line to print the value of sock, and it printed: sock = -1
It seems that new version of xmpppy doesn't support that method, 
although doesn't give an error when using it.

**Comment by gdt** [comment]
> Hi. Apologies for the delay. Is it this fix you are waiting for?
> 
>     * [Fixes AttributeError: module 'ssl' has no attribute 'wrap_socket' #70](https://github.com/xmpppy/xmpppy/pull/70)

Yes, and thank you very much for attending to to xmppy!

**Comment by gdt** [comment]
I took the repro code, changed the domain/username/password and connected to a test account.  I got -1 printed.

Reading code, I wonder if converting to tls is a factor.  I see the code trying to keep track of the socket, but when doing tls wrap it becomes a little too complicated for me to be sure I'm reading it right, without printf instrumenting.  If you can easily test w/o tls, it would be interesting to know if you get the same -1 or not.

**Comment by normanr** [comment]
What happens if you try something like `client.Connection_sslObj.fileno()`?

**Comment by aelmahmoudy** [comment]
@normanr said:
> What happens if you try something like `client.Connection._sslObj.fileno()`?

I get what seems to be a valid fd, yet I get some new errors. I'll 
continue to try porting the script to python3 to check.

**Comment by aelmahmoudy** [comment]
My issue got fixed indeed. Thanks.
-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by gdt** [comment]
I don't know why you closed the issue, just because you figured out a workaround.   Does your new code work if the server connection is *not* TLS?

Really xmppy should have a documented API method.

**Comment by aelmahmoudy** [comment]
@gdt said:
> I don't know why you closed the issue, just because you figured out a workaround. 

The code was using an internal API from the beginning

@gdt said:
> Does your new code work if the server connection is *not* TLS?

No

It would be better indeed if xmpppy would provide some public method 
that returns the socket fd, wether it was a TLS or non-TLS connection.

-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by amotl** [comment]
Hi again. So the idea is to provide a method that would either return `self.client.Connection._sock.fileno()` or `self.client.Connection._sslObj.fileno()`, based on whether it is a plaintext- or SSL-based connection?

**Comment by amotl** [comment]
I only now see that @gdt already created GH-76 about tracking this. Thanks!
