### PR TITLE
Fixes AttributeError: module 'ssl' has no attribute 'wrap_socket'

### PR DESCRIPTION
**Pull request by juanvalino**
Fixes https://github.com/xmpppy/xmpppy/issues/69

### CODE REVIEW

File: xmpp/transports.py [hunk 1]
```diff
@@ -384,7 +384,10 @@ def _startSSL(self):
         """ Immidiatedly switch socket to TLS mode. Used internally."""
         """ Here we should switch pending_data to hint mode."""
         tcpsock=self._owner.Connection
-        tcpsock._sslObj    = ssl.wrap_socket(tcpsock._sock, None, None)
+        context=ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
+        context.check_hostname = False
```
Comment (gdt) [inline xmpp/transports.py:388]: It strikes me that xmppy should by default do TLS validation, and perhaps have an option not to, for people dealing with  their own servers that are not set up correctly.   It may be that this code change replicates the old behavior, in which my comment is unrelated to your PR.

Comment (juanvalino) [reply xmpp/transports.py:388]: I tried to make the minimal changes to get the library work in python 3.12, as some ssl library functions were removed and I think this is equivalent to previous code. I'm missing something?

**Comment by juanvalino** [comment]
I've updated PR disabling certificate checking to maintain backward compability

**Comment by juanvalino** [comment]
@gdt I`m going to create a new issue to ask for an explicit and configurable way to enable/disable certificate checking, but I think this fix should be enough to get the library work with latest python versions maintaining previous behavior.

**Comment by gdt** [comment]
Fair enough to match previous behavior.   My comment was mainly aimed at "As a reviewer, it should be clear whether this is a change or not".

Secondarily, I think defaulting to not validating is a bug.

**Comment by juanvalino** [comment]
@gdt I think that defaulting to not validating is no ideal (security matters) but necessary if we want to maintain previous behavior because when creating a default context and using context's wrap_socket always did certificate validation (since Python 2.7.x for some x < 20 IIRC). But the xmpppy library uses the top-level wrap_socket function, which got removed in Python 3.12; that one never did certificate validation.

So the way I understand it, with Python < 3.12 xmpppy doesn't seem to validate certificates, and with Python >= 3.12 it doesn't work if you use TLS (because the function it uses was removed).

**Review by felixfontein — APPROVED** [review]
The change looks correct to me. I agree that enabling certificate validation by default would be better, but this didn't happen before.

This PR might cause problems with very early 2.7.x releases, since the `ssl` module changed a lot for the first couple of `x`. This has been a looong time ago, though, so I think it's OK to ignore that :)

**Comment by juanvalino** [comment]
Please, anyone could merge the proposed patch and release a new version with this fixed? 

More than one year with the solution ready...

**Comment by glefait** [comment]
@juanvalino , I feel you and thanks for your patch.

An alternative, when security is not a concern (like in a lab) and until this PR is merged, is to use `secure=0`. 
https://github.com/glefait/CVE-2023-25355-25356/blob/main/src/main.py#L48

If I were to use this library in a "real" context (not in a lab), I would probably prefer to be able to control specifically which security flag is ignored.

File: xmpp/transports.py [hunk 2]
```diff
@@ -386,6 +386,7 @@ def _startSSL(self):
         tcpsock=self._owner.Connection
         context=ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
         context.check_hostname = False
+        context.verify_mode = ssl.CERT_NONE
```
[the remark this answers is not in the document]
Comment (felixfontein) [reply xmpp/transports.py:389]: If you want to enable certificate checking, better create `context` with `ssl.create_default_context()` (https://docs.python.org/3/library/ssl.html#ssl.create_default_context), and don't manually call `set_default_verify_paths` and set `check_hostname` and `verify_mode`.

[the remark this answers is not in the document]
Comment (gdt) [reply xmpp/transports.py:389]: Thanks - I have changed pkgsrc as you suggest.
